# Generated by Django 2.0.13 on 2019-09-27 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='secretaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_secretaire', to=settings.AUTH_USER_MODEL),
        ),
    ]
