# Generated by Django 2.0.13 on 2019-10-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20190927_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='description',
        ),
    ]
