# Generated by Django 2.0.13 on 2019-10-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_remove_case_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
