# Generated by Django 2.0.13 on 2019-10-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_case_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.CharField(default=None, max_length=500, verbose_name='consultation'),
        ),
    ]
