# Generated by Django 3.2 on 2023-06-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20191001_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
